# Generated by Django 3.1.2 on 2021-10-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Descreption',
            new_name='info',
        ),
    ]
