# Generated by Django 3.1.2 on 2021-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211023_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=15, upload_to='pics', width_field=10),
        ),
    ]
